
services:

  php:
    image: 'mautic-php-6.0.x'
    build:
      context: docker/conf/php
      dockerfile: Dockerfile
    volumes:
      - '.:/srv/mautic'
    networks:
      - 'app-network'
    depends_on:
      - 'mysql'

  mysql:
    build:
      context: docker/conf/mysql
      dockerfile: Dockerfile
    command: '--default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: '${APP_DATABASE_NAME:-mautic}'
      MYSQL_USER: '${APP_DATABASE_USER:-mautic}'
      MYSQL_PASSWORD: '${APP_DATABASE_PASSWORD:-mautic}'
    volumes:
      - './docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro'
      - './docker/volumes/database:/var/lib/mysql:z'
    ports:
      - '${DOCKER_PORT_MYSQL:-33006}:3306'
    networks:
      - 'app-network'

  nginx:
    image: nginx
    ports:
      - '8081:80'
    volumes:
      - '.:/srv/mautic'
      - './docker/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      - 'app-network'
    depends_on:
      - php

networks:
  app-network: