
services:

  php:
    image: 'mautic-php-6.0.x'
    build:
      context: docker/conf/php
      dockerfile: Dockerfile
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=mautic-docker-cli'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: 'client_host=172.17.0.1'
    volumes:
      - '.:/srv/mautic'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/mautic'
    command: 'php'
    user: 'www-data'
    init: true
    networks:
      - 'app-network'
    depends_on:
      - 'mysql'
  fpm:
    image: 'mautic-php-6.0.x'
    build:
      context: docker/conf/php
      dockerfile: Dockerfile
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
      PHP_IDE_CONFIG: 'serverName=mautic-docker-web-2'
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
#      XDEBUG_CONFIG: 'client_host=172.17.0.1'
      NPM_CONFIG_CACHE: /var/www/.npm
    volumes:
      - '.:/srv/mautic'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
    working_dir: '/srv/mautic'
    command: 'php-fpm -F'
    networks:
      - 'app-network'
    depends_on:
      - 'mysql'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    build:
      context: docker/conf/mysql
      dockerfile: Dockerfile
    command: '--default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: '${APP_DATABASE_NAME:-mautic}'
      MYSQL_USER: '${APP_DATABASE_USER:-mautic}'
      MYSQL_PASSWORD: '${APP_DATABASE_PASSWORD:-mautic}'
    volumes:
      - './docker/mysql/initdb.d:/docker-entrypoint-initdb.d:ro'
      - './docker/volumes/database:/var/lib/mysql:z'
    ports:
      - '${DOCKER_PORT_MYSQL:-33006}:3306'
    networks:
      - 'app-network'

  nginx:
    image: nginx
    ports:
      - '81:80'
    volumes:
      - '.:/srv/mautic'
      - './docker/conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      - 'app-network'
    depends_on:
      - php

networks:
  app-network: